// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"mango/config"
	"mango/internal/app"
	"mango/internal/controller"
	"mango/internal/repository"
	"mango/internal/server"
	"mango/internal/service"

	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序
func InitializeApp(configPath string) (*app.App, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return nil, err
	}
	//db, err := provideDB(configConfig)
	if err != nil {
		return nil, err
	}
	db := &gorm.DB{}
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := controller.NewUserHandler(userService)
	textRiskLogRepository := repository.NewTextRiskLogRepository(db)
	textRiskLogService := service.NewTextRiskLogService(textRiskLogRepository)
	volcHandler := controller.NewVolcHandler(userService, textRiskLogService)
	voiceHandler := controller.NewVoiceHandler(userService)
	zhiPuHandler := controller.NewZhiPuHandler(userService, textRiskLogService)
	algorithmHandler := controller.NewAlgorithmHandler(userService)
	v := provideHandlers(userHandler, volcHandler, voiceHandler, zhiPuHandler, algorithmHandler)
	serverServer := server.NewServer(configConfig, v...)
	appApp := app.NewApp(configConfig, serverServer)
	return appApp, nil
}

// wire.go:

// provideDB 提供数据库连接
func provideDB(config2 *config.Config) (*gorm.DB, error) {
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local", config2.
		Database.Username, config2.
		Database.Password, config2.
		Database.Host, config2.
		Database.Port, config2.
		Database.DBName,
	)
	return gorm.Open(mysql.Open(dsn), &gorm.Config{})
}

func provideHandlers(userHandler *controller.UserHandler, volcHandler *controller.VolcHandler, voiceHandler *controller.VoiceHandler, zhipuHandler *controller.ZhiPuHandler, algorithmHandler *controller.AlgorithmHandler) []controller.Handler {
	return []controller.Handler{userHandler, volcHandler, voiceHandler, zhipuHandler, algorithmHandler}
}
